
- name: copy installer
  ansible.builtin.copy:
    src: install_cert-manager.sh
    dest: /opt/install_scripts/install_cert-manager.sh
    owner: pi
    group: pi

- name: copy specs
  ansible.builtin.copy:
    src: specs/cert-manager.crds.yaml
    dest: /opt/install_scripts/specs/cert-manager.crds.yaml
    owner: pi
    group: pi

- name: install
  shell: sh /opt/install_scripts/install_cert-manager.sh
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: wait for port 443
  wait_for:
    port: 443
    delay: 10
