
- name: copy helm installer
  ansible.builtin.copy:
    src: get_helm.sh
    dest: /opt/install_scripts/get_helm.sh
    owner: pi
    group: pi

- name: is helm there?
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_bin

- name: install helm if needed
  shell: 'sh /opt/install_scripts/get_helm.sh'
  when:
    - helm_bin.stat.exists == False

