
- name: update cache if 10 days old
  apt:
    update_cache: yes
    cache_valid_time: 864000

- name: install some common packages
  apt:
    pkg:
      - curl
      - nmap
      - telnet
      - dnsutils
    state: present
