  - name: set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname_short }}"

  - name: place hostname file
    template:
      src: "hostname.txt"
      dest: /etc/hostname


  - name: place hosts file
    template:
      src: "hosts.txt"
      dest: /etc/hosts
